DROP TABLE IF EXISTS produtos;
DROP TABLE IF EXISTS contas;

CREATE TABLE produtos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    produto TEXT NOT NULL,
    descricao TEXT NOT NULL,
    preco INTERGER NOT NULL,
    estoqueLoja TEXT NOT NULL,
    departamentos TEXT NOT NULL,
    anexos TEXT NOT NULL
);

CREATE TABLE user (
	id INTEGER NOT NULL, 
	nome VARCHAR(20) NOT NULL, 
	username VARCHAR(20) NOT NULL,
	password VARCHAR(80) NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (username)
);

CREATE TABLE setores (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    setor TEXT NOT NULL,
    vf TEXT NOT NULL
);

